
package rayin.credit;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilum
 */public class Adimin_login extends javax.swing.JFrame {

    /**
     * Creates new form Adimin_login
     */
    public Adimin_login() {
        initComponents();
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
//        lbl_userName.setVisible(false);
  //      userName_box.setVisible(false);
    }
    //Logger.getLogger(Adimin_login.class.getName()).log(Level.SEVERE, null, ex);
    static int passwordok = 0;
    boolean admin = true;
    dbConnector connect = new dbConnector();

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clogbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        signin = new javax.swing.JButton();
        text_user = new javax.swing.JLabel();
        img_logo = new javax.swing.JLabel();
        forget = new javax.swing.JLabel();
        apasslogo = new javax.swing.JLabel();
        text_user2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Clogbtn.setText("Sign In");
        Clogbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Clogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClogbtnActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RAYIN CREDIT");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 576, 46));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("- By Evon Apps ... -");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 171, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME TO ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 588, 46));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Evon Apps");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 20, 222, 24));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 0));

        jPanel2.setBackground(new java.awt.Color(2, 35, 35));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 316, 279, 37));

        signin.setBackground(new java.awt.Color(0, 204, 204));
        signin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("Sign In");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel2.add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 371, 141, 36));

        text_user.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        text_user.setForeground(new java.awt.Color(255, 255, 255));
        text_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_user.setText("Adminstrator ");
        jPanel2.add(text_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 303, -1));

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("admin.png")));
        img_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_logoMouseClicked(evt);
            }
        });
        jPanel2.add(img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 74, -1, 187));

        forget.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        forget.setForeground(new java.awt.Color(255, 255, 255));
        forget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forget.setText("Forget password ");
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetMouseClicked(evt);
            }
        });
        jPanel2.add(forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 425, 279, -1));

        apasslogo.setBackground(new java.awt.Color(255, 255, 255));
        apasslogo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        apasslogo.setForeground(new java.awt.Color(255, 255, 0));
        apasslogo.setText("Password : ");
        jPanel2.add(apasslogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 288, 245, 22));

        text_user2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        text_user2.setForeground(new java.awt.Color(255, 255, 255));
        text_user2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_user2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rayin/credit/admin.png"))); // NOI18N
        jPanel2.add(text_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 80, 210, 196));

        jTabbedPane1.addTab("Admin", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 310, 480));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Admin");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("login background.jpg")));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 970, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClogbtnActionPerformed

    }//GEN-LAST:event_ClogbtnActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        //setting loging pannel to defult login process
        apasslogo.setText("Password : ");
        passwordok = 0;
        signin.setText("Sign In");
        forget.setText("Forget password ");

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
         //setting loging pannel to defult login process
       defaults();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //setting loging pannel to defult login process
       defaults();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        //setting loging pannel to defult login process
        defaults();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked

        signin.setText("CHEK");
        apasslogo.setText("Enter Security Question .");
        passwordok = 1;
    }//GEN-LAST:event_forgetMouseClicked

    private void img_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_logoMouseClicked
        //setting loging pannel to defult login process
        defaults();
    }//GEN-LAST:event_img_logoMouseClicked

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed

        //sign in process
        signin();
    }//GEN-LAST:event_signinActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        int lenth = String.copyValueOf(password.getPassword()).length();
        char enter = evt.getKeyChar();
        if(lenth ==254)
        {

            evt.consume();
        }

        if(enter == KeyEvent.VK_ENTER)
        {
            signin();
        }
    }//GEN-LAST:event_passwordKeyTyped

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    //defaults state of admin logn window
    void defaults()
        {
               //setting loging pannel to defult login process
                apasslogo.setText("Password : ");
                passwordok = 0;
                signin.setText("Sign In");
                forget.setText("Forget password ");
        }
    
 //sign inn process
    void signin()
        {        
            if(!String.valueOf(password.getPassword()).isEmpty())
                {
                    if(passwordok == 0) //if user directly enter the password (default state)
                    {
                    
                            String passis = String.valueOf(password.getPassword());

                            Encoder convert = new Encoder();

                            try {
                                boolean passOk = connect.passchek(convert.getMd5(passis));

                                if(passOk == true)
                                {
                                    //opening main menu
                                    apasslogo.setText("Password : ");
                                    MainFrame open = new MainFrame();
                                    open.setVisible(true);
                                    controllers.systemUser = false; // for stop recoding activites
                                    System.gc();
                                    dispose();
                                }
                                else
                                {
                                    apasslogo.setText("Password incorrect !");
                                    password.setText("");
                                }

                            } catch (Exception ex) {
                               JOptionPane.showMessageDialog(null,"Something went wrong - Admin-login#612 ");
                            }
                      }
                  else if(passwordok == 1) //user forgot the password ans enter the securty key and trying to chek
                        {
                                    String question = String.valueOf(password.getPassword());
                                    
                                    try {
                                        boolean qesok = connect.questionchek(question , 1); //cheking the avaiability of security question
                                        
                                        if(qesok == true) //if question is availble letting to enter the answer
                                            {
                                                apasslogo.setText("Enter the answer .");
                                                password.setText("");
                                                passwordok = 2; //setting sign in btn state to chek the answer validity
                                            }
                                        else
                                            {
                                                apasslogo.setText("Incorrect Security Question !");
                                                password.setText("");
                                            }
                                        
                                    } catch (Exception ex) {
                                       JOptionPane.showMessageDialog(null,"Something went wrong - Admin-login#635 ");
                                    }
                                }
                  else  //state of ready to chek security answer
                    {
                                try {
                                        String answer = String.valueOf(password.getPassword());
                                        boolean qesok = connect.questionchek(answer , 2);
                                        
                                        if(qesok == true) // id answer is ok the open the setting window 
                                            {
                                               passwordok = 0; //setting sign in btn state to chek the answer validity
                                               settings open = new settings();
                                               open.setVisible(true);
                                               setVisible(false);
                                            }
                                        else
                                            {
                                                apasslogo.setText("incorrect Answer!");
                                                password.setText("");
                                            }
                                        
                                    } catch (Exception ex) {
                                       JOptionPane.showMessageDialog(null,"Something went wrong - Admin-login#658 ");
                                    }
                    }
                }
        }

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null , "Something went wrong admin-login#701");
            dbConnector connect = new dbConnector();
        } 
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adimin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clogbtn;
    public static javax.swing.JLabel apasslogo;
    public static javax.swing.JLabel forget;
    private javax.swing.JLabel img_logo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signin;
    private javax.swing.JLabel text_user;
    private javax.swing.JLabel text_user2;
    // End of variables declaration//GEN-END:variables
}
