package rayin.credit;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dilum
 */
public class newRep extends javax.swing.JFrame {

    /**
     * Creates new form BillOwner
     */
    
    boolean who = true; //true means new borrower update // false for new cashier
    
    public newRep(String typeis) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        changephoneno.setEnabled(false);
        next.setEnabled(false);
        type.setSelectedItem(typeis);
        type.setEnabled(false);
    }
    
     public newRep(boolean cashier ) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ok.png")));
        lbl_name.setText("Cashier Name");
        lbl_address.setText("Address");
        lbl_phone.setText("Phone");
        next.setText("ADD");
        changephoneno.setEnabled(false);
        next.setEnabled(false);
        this.who = false;
    }

    dbConnector connect = new dbConnector();
    String table = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cusphoneFor = new javax.swing.JTextField();
        CusName = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        lbl_phone = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        changephoneno = new javax.swing.JButton();
        lbl_address = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        lbl_name1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Name & Phone Number ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        cusphoneFor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cusphoneFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusphoneForActionPerformed(evt);
            }
        });
        cusphoneFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cusphoneForKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cusphoneForKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cusphoneForKeyTyped(evt);
            }
        });

        CusName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNameActionPerformed(evt);
            }
        });
        CusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CusNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CusNameKeyTyped(evt);
            }
        });

        next.setBackground(new java.awt.Color(0, 204, 51));
        next.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        lbl_phone.setBackground(new java.awt.Color(255, 255, 255));
        lbl_phone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(255, 255, 255));
        lbl_phone.setText("Rep Phone Number");

        lbl_name.setBackground(new java.awt.Color(255, 255, 255));
        lbl_name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Rep Name");

        changephoneno.setBackground(new java.awt.Color(0, 51, 51));
        changephoneno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        changephoneno.setText("Change");
        changephoneno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changephoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changephonenoActionPerformed(evt);
            }
        });

        lbl_address.setBackground(new java.awt.Color(255, 255, 255));
        lbl_address.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(255, 255, 255));
        lbl_address.setText("Rep Type");

        type.setBackground(new java.awt.Color(0, 0, 51));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FOOD", "AGROMA" }));

        lbl_name1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_name1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lbl_name1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name1.setText("ADD NEW REP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cusphoneFor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(changephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lbl_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusphoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNameActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

            try {
            //calling processing method name send data;
            sendData();
            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(null, "Something went wrong  !");
                Logger.getLogger(newRep.class.getName()).log(Level.SEVERE, null, ex);

            }

    }//GEN-LAST:event_nextActionPerformed

    private void CusNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CusNameKeyTyped
        char c = evt.getKeyChar();
        String lenth = CusName.getText();

        if (lenth.length() == 250) //setting the maximum range of customer name 
        {
            evt.consume();
        }

        if ((Character.isLetter(c)) || (Character.isWhitespace(c)) || (Character.isISOControl(c))) {
            CusName.setEditable(true);

        } else {
            evt.consume();

        }

    }//GEN-LAST:event_CusNameKeyTyped

    private void cusphoneForKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusphoneForKeyTyped
        char c = evt.getKeyChar();

        if ((Character.isDigit(c)) || (Character.isISOControl(c))) {
            cusphoneFor.setEnabled(true);
        } else {
            evt.consume();
        }

        if (c == KeyEvent.VK_ENTER) {
            try {
                //calling processing method name send data;
                sendData();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Something went wrong !");

               // Logger.getLogger(newEmplyoee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_cusphoneForKeyTyped

    private void cusphoneForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusphoneForKeyReleased
        String lenth = cusphoneFor.getText();
        if ((lenth.length() == 10) || (lenth.length() == 0)) {
            lbl_phone.setText("Phone Number ok !");
            next.setEnabled(true);
            cusphoneFor.setEnabled(false);
            changephoneno.setEnabled(true);
        } else {
            next.setEnabled(false);
        }

        try {
            char[] c = lenth.toCharArray();
            if (c[0] != '0') {
                lbl_phone.setText("Invalid Phone Number !");
                next.setEnabled(false);
            } else {
                lbl_phone.setText("Phone Number : ");
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_cusphoneForKeyReleased

    private void changephonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changephonenoActionPerformed
        cusphoneFor.setText("");
        cusphoneFor.setEnabled(true);
        changephoneno.setEnabled(false);
    }//GEN-LAST:event_changephonenoActionPerformed

    private void cusphoneForKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusphoneForKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusphoneForKeyPressed

    private void CusNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CusNameKeyReleased
        String lenth = CusName.getText();
        if (lenth.length() >= 2) {
            next.setEnabled(true);
        } else {
            next.setEnabled(false);
        }
    }//GEN-LAST:event_CusNameKeyReleased

    private void cusphoneForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusphoneForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusphoneForActionPerformed

   
    
  //process of new employee
     void sendData() throws Exception {

         if(CusName.getText().length()>0)
         {
             String [] namePhoneNic = {CusName.getText().trim()  , cusphoneFor.getText() , type.getSelectedItem().toString()};

               //sending new borrower to database
               connect.addNewCasher(namePhoneNic); // storing borrrower to db

               System.gc();
               dispose();
         }
         else
         {
             JOptionPane.showMessageDialog(null, "Please add Rep Name !");
         }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        dbConnector connect= new dbConnector();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
          
            JOptionPane.showMessageDialog(null, "Something went wrong  !");
           // java.util.logging.Logger.getLogger(newEmplyoee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newRep("").setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CusName;
    private javax.swing.JButton changephoneno;
    private javax.swing.JTextField cusphoneFor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JButton next;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
