package rayin.credit;


import java.awt.Toolkit;
import javax.swing.JOptionPane;
//Logger.getLogger(UpdateBorrowers.class.getName()).log(Level.SEVERE, null, ex);

public class UpdateReps extends javax.swing.JFrame {

    /**
     * Creates new form stock_item_display
     */
    int whichPanel = 0; //true for borrower update anf false for cashier update
    String newType = "";

    //BORROWER HUPDATE HANDLING WINDOW
    public UpdateReps(String code, String nameis, String tp, String typeis) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));

        newType = typeis;
        name.setText(nameis);
        contact.setText(tp);
        type.setSelectedItem(typeis);

        name.setEditable(false);
        contact.setEditable(false);
        type.setEnabled(false);

        nameUpdate.setEnabled(false);
        contactUpdate.setEnabled(false);
        typeUpdate.setEnabled(false);

        this.primarykeyofdata = code;
        newType = typeis;
    }

    dbConnector connect = new dbConnector();

    String primarykeyofdata;
    String WhatIsCondition;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panel_name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        CloseUpdatePannel = new javax.swing.JButton();
        nameedit = new javax.swing.JButton();
        nameUpdate = new javax.swing.JButton();
        conditionedit = new javax.swing.JButton();
        contactUpdate = new javax.swing.JButton();
        contact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        conditionedit1 = new javax.swing.JButton();
        typeUpdate = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();

        jTextField9.setText("jTextField1");

        jTextField10.setText("jTextField1");

        jButton6.setText("jButton2");

        jButton8.setText("jButton2");

        jButton19.setText("jButton19");

        setTitle("Item Viewer");
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        panel_name.setBackground(new java.awt.Color(255, 255, 255));
        panel_name.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        panel_name.setForeground(new java.awt.Color(255, 255, 255));
        panel_name.setText("Update Reps");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("NAME");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contact");

        name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        CloseUpdatePannel.setBackground(new java.awt.Color(0, 102, 51));
        CloseUpdatePannel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CloseUpdatePannel.setForeground(new java.awt.Color(255, 255, 255));
        CloseUpdatePannel.setText("CLOSE  PANNEL");
        CloseUpdatePannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        CloseUpdatePannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseUpdatePannelActionPerformed(evt);
            }
        });

        nameedit.setBackground(new java.awt.Color(255, 0, 0));
        nameedit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameedit.setForeground(new java.awt.Color(255, 255, 255));
        nameedit.setText("Edit");
        nameedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeditActionPerformed(evt);
            }
        });

        nameUpdate.setBackground(new java.awt.Color(0, 153, 204));
        nameUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameUpdate.setText("UPDATE");
        nameUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUpdateActionPerformed(evt);
            }
        });

        conditionedit.setBackground(new java.awt.Color(255, 0, 0));
        conditionedit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        conditionedit.setForeground(new java.awt.Color(255, 255, 255));
        conditionedit.setText("Edit");
        conditionedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditioneditActionPerformed(evt);
            }
        });

        contactUpdate.setBackground(new java.awt.Color(0, 153, 204));
        contactUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contactUpdate.setText("UPDATE");
        contactUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactUpdateActionPerformed(evt);
            }
        });

        contact.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Type");

        conditionedit1.setBackground(new java.awt.Color(255, 0, 0));
        conditionedit1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        conditionedit1.setForeground(new java.awt.Color(255, 255, 255));
        conditionedit1.setText("Edit");
        conditionedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionedit1ActionPerformed(evt);
            }
        });

        typeUpdate.setBackground(new java.awt.Color(0, 153, 204));
        typeUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        typeUpdate.setText("UPDATE");
        typeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUpdateActionPerformed(evt);
            }
        });

        type.setBackground(new java.awt.Color(0, 0, 51));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FOOD", "AGROMA" }));
        type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(280, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(conditionedit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contactUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(conditionedit1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(typeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nameedit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(CloseUpdatePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name)
                    .addComponent(nameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(conditionedit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(type))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contact)
                    .addComponent(contactUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conditionedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(CloseUpdatePannel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseUpdatePannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseUpdatePannelActionPerformed
        try {
            connect.search_all_deals(newType);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong !");

        }

        System.gc();
        this.dispose();

    }//GEN-LAST:event_CloseUpdatePannelActionPerformed

    private void nameeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeditActionPerformed
        name.setEditable(true);
        contact.setEditable(false);
        type.setEditable(false);

        nameUpdate.setEnabled(false);
        contactUpdate.setEnabled(false);
        typeUpdate.setEnabled(false);
    }//GEN-LAST:event_nameeditActionPerformed

    private void conditioneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditioneditActionPerformed
        name.setEditable(false);
        contact.setEditable(true);
        type.setEditable(false);

        nameUpdate.setEnabled(false);
        contactUpdate.setEnabled(false);
        typeUpdate.setEnabled(false);

    }//GEN-LAST:event_conditioneditActionPerformed

    private void nameUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUpdateActionPerformed
        try {

            connect.updateBorrowerData("RepName", name.getText().trim(), primarykeyofdata, 0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong !");

        }

        nameUpdate.setEnabled(false);
        name.setEditable(false);
    }//GEN-LAST:event_nameUpdateActionPerformed

    private void contactUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactUpdateActionPerformed

        try {

            connect.updateBorrowerData("Phone", contact.getText().trim(), primarykeyofdata, 0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong !");

        }

        contact.setEditable(false);
        contactUpdate.setEnabled(false);

    }//GEN-LAST:event_contactUpdateActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        char character = evt.getKeyChar();
        String lenth = name.getText();

        if (lenth.length() == 100) {
            evt.consume();
        }

        if ((Character.isLetter(character)) || Character.isWhitespace(character) || Character.isISOControl(character) && lenth.length() > 1) {
            name.setEnabled(true);
            nameUpdate.setEnabled(true);
        } else {
            evt.consume();
            nameUpdate.setEnabled(false);
        }
    }//GEN-LAST:event_nameKeyTyped

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        String lenth = name.getText();

        if (lenth.length() > 0) {
            nameUpdate.setEnabled(true);
        } else {
            nameUpdate.setEnabled(false);
        }
    }//GEN-LAST:event_nameKeyReleased

    private void contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyReleased
        String lenth = contact.getText();

        if (lenth.length() == 10 || lenth.length() == 0) {
            contactUpdate.setEnabled(true);
        } else {
            contactUpdate.setEnabled(false);
        }


    }//GEN-LAST:event_contactKeyReleased

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char c = evt.getKeyChar();

        if ((Character.isDigit(c)) || (Character.isISOControl(c))) {
            contact.setEnabled(true);
        } else {
            evt.consume();
        }

        if (contact.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_contactKeyTyped

    private void conditionedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionedit1ActionPerformed
        name.setEditable(false);
        contact.setEditable(false);
        type.setEnabled(true);

        nameUpdate.setEnabled(false);
        contactUpdate.setEnabled(false);
        typeUpdate.setEnabled(true);
    }//GEN-LAST:event_conditionedit1ActionPerformed

    private void typeUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUpdateActionPerformed
        try {

            connect.updateBorrowerData("Type", type.getSelectedItem().toString(), primarykeyofdata, 0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong !");

        }

        typeUpdate.setEnabled(false);
        type.setEnabled(false);
    }//GEN-LAST:event_typeUpdateActionPerformed

    private void typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeItemStateChanged
        typeUpdate.setEnabled(true);
    }//GEN-LAST:event_typeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        dbConnector connect = new dbConnector();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong !");

        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UpdateReps("", "", "", "").setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Something went wrong !");
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseUpdatePannel;
    private javax.swing.JButton conditionedit;
    private javax.swing.JButton conditionedit1;
    private javax.swing.JTextField contact;
    private javax.swing.JButton contactUpdate;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField name;
    private javax.swing.JButton nameUpdate;
    private javax.swing.JButton nameedit;
    private javax.swing.JLabel panel_name;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton typeUpdate;
    // End of variables declaration//GEN-END:variables
}
